# Generated by Django 5.1.15 on 2026-03-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0001_initial'),
        ('qr_codes', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, help_text='Formato: TK-000001. Secuencial global.', max_length=20, unique=True, verbose_name='Número de ticket')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cooperativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='cooperativas.cooperativa', verbose_name='Cooperativa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('ticket_qr', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='qr_codes.ticketqr', verbose_name='Ticket QR')),
                ('tipo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tickets.tipoticket', verbose_name='Tipo de ticket')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['operador', 'fecha'], name='ventas_vent_operado_52b3b9_idx'), models.Index(fields=['tipo_ticket', 'fecha'], name='ventas_vent_tipo_ti_bf31a8_idx'), models.Index(fields=['cooperativa', 'fecha'], name='ventas_vent_coopera_d9bc0b_idx')],
            },
        ),
    ]
