# Generated by Django 5.1.15 on 2026-03-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('max_boletos', models.PositiveIntegerField(default=0, help_text='0 = sin límite', verbose_name='Máximo de boletos')),
                ('boletos_utilizados', models.PositiveIntegerField(default=0, verbose_name='Boletos utilizados')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cooperativa',
                'verbose_name_plural': 'Cooperativas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='cooperativa_estado_21dbdc_idx')],
            },
        ),
    ]
