# Generated by Django 5.1.15 on 2026-03-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativas', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHikvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Torniquete Principal', max_length=100, verbose_name='Nombre del dispositivo')),
                ('ip', models.CharField(max_length=50, verbose_name='Dirección IP')),
                ('puerto', models.PositiveIntegerField(default=80, verbose_name='Puerto')),
                ('protocolo', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=10, verbose_name='Protocolo')),
                ('usuario', models.CharField(default='admin', max_length=50, verbose_name='Usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('puerta', models.PositiveIntegerField(default=1, verbose_name='Número de puerta')),
                ('minutos_expiracion_default', models.PositiveIntegerField(default=10, verbose_name='Minutos de expiración por defecto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Hikvision',
                'verbose_name_plural': 'Configuración Hikvision',
            },
        ),
        migrations.CreateModel(
            name='TicketQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='employeeNo y cardNo enviado a Hikvision', max_length=50, unique=True, verbose_name='Código único')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio cobrado')),
                ('minutos_expiracion', models.PositiveIntegerField(verbose_name='Minutos de expiración')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_expiracion', models.DateTimeField(db_index=True, verbose_name='Fecha de expiración')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('error', 'Error')], db_index=True, default='activo', max_length=10, verbose_name='Estado')),
                ('imagen_qr_base64', models.TextField(help_text='data:image/png;base64,...', verbose_name='Imagen QR (base64)')),
                ('hik_usuario_ok', models.BooleanField(default=False, verbose_name='Usuario Hikvision creado')),
                ('hik_tarjeta_ok', models.BooleanField(default=False, verbose_name='Tarjeta QR asignada en Hikvision')),
                ('hik_respuesta', models.TextField(blank=True, verbose_name='Respuesta Hikvision (raw)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de uso')),
                ('cooperativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_qr', to='cooperativas.cooperativa', verbose_name='Cooperativa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_generados', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('tipo_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_qr', to='tickets.tipoticket', verbose_name='Tipo de ticket')),
            ],
            options={
                'verbose_name': 'Ticket QR',
                'verbose_name_plural': 'Tickets QR',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_expiracion'], name='qr_codes_ti_estado_ad494f_idx'), models.Index(fields=['operador', 'fecha_creacion'], name='qr_codes_ti_operado_0ee2d8_idx')],
            },
        ),
    ]
