# Generated by Django 5.1.15 on 2026-03-12 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_contenido', models.CharField(max_length=100, verbose_name='Contenido del QR')),
                ('resultado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], max_length=10, verbose_name='Resultado')),
                ('razon', models.CharField(blank=True, max_length=200, verbose_name='Razón')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='qr_codes.ticketqr', verbose_name='Ticket QR')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha', 'resultado'], name='accesos_acc_fecha_538c7e_idx')],
            },
        ),
    ]
